import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navbar />
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: March 2, 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Service Description</h2>
            <p className="text-muted-foreground leading-relaxed">
              War Impact Report provides AI-generated business impact assessments related to the 2026 Iran War and Strait of Hormuz crisis. Our reports are generated using artificial intelligence and publicly available data sources. They are intended for informational purposes only and should not be considered as financial, legal, or professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Report Accuracy</h2>
            <p className="text-muted-foreground leading-relaxed">
              While we strive for accuracy, our reports are generated by AI models and may contain errors or outdated information. The geopolitical situation is rapidly evolving, and data may change between report generation and delivery. Users should verify critical information through independent sources before making business decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Pricing and Payments</h2>
            <p className="text-muted-foreground leading-relaxed">
              Free reports are available at no cost. Full reports are available for a one-time payment of $49 USD. Weekly update subscriptions are available for $19 USD per month and can be cancelled at any time. All payments are processed securely through Stripe. Refunds are available within 7 days of purchase if you are unsatisfied with the report quality.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              Generated reports are provided for your personal or internal business use. You may share report excerpts with attribution. You may not resell, redistribute, or republish complete reports without written permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              War Impact Report and its operators shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of our reports or services. Our maximum liability is limited to the amount paid for the specific report or subscription in question.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Rate Limits</h2>
            <p className="text-muted-foreground leading-relaxed">
              Free reports are limited to 3 per IP address per hour to ensure fair usage and service availability. Abuse of the service, including automated scraping or excessive requests, may result in temporary or permanent access restrictions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the updated terms. We will notify subscribers of material changes via email.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              For questions about these terms, please contact us at legal@warimpactreport.com.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  );
}
