/**
 * PDF Generation Module
 * 
 * Generates branded PDF reports for full intelligence reports.
 * Uses HTML-to-PDF conversion via a simple approach that works server-side.
 */

import { storagePut } from "./storage";
import { nanoid } from "nanoid";

export async function generateReportPdf(params: {
  industry: string;
  country: string;
  companySize: string;
  riskLevel: string;
  content: string;
  reportId: number;
}): Promise<{ url: string; key: string }> {
  const { industry, country, companySize, riskLevel, content, reportId } = params;
  const riskColor = riskLevel === "CRITICAL" ? "#EF4444" : riskLevel === "HIGH" ? "#F59E0B" : riskLevel === "MODERATE" ? "#3B82F6" : "#10B981";
  const generatedDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Convert markdown-like content to basic HTML
  const htmlContent = content
    .replace(/## (\d+)\. (.+)/g, '<h2 style="color:#EF4444;font-size:18px;margin:24px 0 12px;border-bottom:1px solid #374151;padding-bottom:8px;">$1. $2</h2>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/- (.+)/g, '<li style="margin:4px 0;">$1</li>')
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br>");

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @page { margin: 40px 50px; size: A4; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1F2937; line-height: 1.6; font-size: 11px; }
  .header { background: #0A0E17; color: white; padding: 32px; margin: -40px -50px 24px; }
  .header h1 { color: #EF4444; font-size: 22px; margin: 0 0 4px; letter-spacing: 2px; }
  .header .subtitle { color: #9CA3AF; font-size: 12px; }
  .meta-grid { display: flex; gap: 24px; margin: 16px 0 0; }
  .meta-item { }
  .meta-label { color: #6B7280; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; }
  .meta-value { color: #F9FAFB; font-size: 13px; font-weight: 600; }
  .risk-badge { display: inline-block; background: ${riskColor}22; color: ${riskColor}; padding: 4px 16px; border-radius: 4px; font-weight: bold; font-size: 13px; border: 1px solid ${riskColor}44; }
  .content { padding: 0; }
  .content h2 { color: #0A0E17; font-size: 16px; margin: 28px 0 12px; border-bottom: 2px solid #EF4444; padding-bottom: 6px; }
  .content p { margin: 8px 0; }
  .content li { margin: 4px 0; }
  .content strong { color: #0A0E17; }
  .footer { border-top: 1px solid #D1D5DB; padding-top: 16px; margin-top: 32px; color: #6B7280; font-size: 9px; text-align: center; }
  .disclaimer { background: #FEF3C7; border: 1px solid #F59E0B; border-radius: 4px; padding: 12px; margin: 24px 0; font-size: 10px; color: #92400E; }
</style>
</head>
<body>
  <div class="header">
    <h1>WAR IMPACT REPORT</h1>
    <div class="subtitle">Full Intelligence Report — Iran War & Strait of Hormuz Crisis</div>
    <div class="meta-grid">
      <div class="meta-item">
        <div class="meta-label">Industry</div>
        <div class="meta-value">${industry}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Country</div>
        <div class="meta-value">${country}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Company Size</div>
        <div class="meta-value">${companySize}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Risk Level</div>
        <div class="risk-badge">${riskLevel}</div>
      </div>
    </div>
    <div style="margin-top:12px;">
      <div class="meta-label">Generated</div>
      <div class="meta-value">${generatedDate}</div>
    </div>
  </div>

  <div class="content">
    <p>${htmlContent}</p>
  </div>

  <div class="disclaimer">
    <strong>Disclaimer:</strong> This report is generated by AI analysis and should be used as one input among many in business decision-making. 
    Data is sourced from public reports, commodity exchanges, shipping databases, and government publications. 
    Verify critical decisions with qualified advisors.
  </div>

  <div class="footer">
    <p>War Impact Report — Report #${reportId} — Generated ${generatedDate}</p>
    <p>warimpactreport.com | Powered by AI Intelligence</p>
    <p>This document is confidential and intended for the recipient only.</p>
  </div>
</body>
</html>`;

  // Store the HTML as a file that can be converted to PDF
  // For production, you'd use a headless browser or wkhtmltopdf
  // For now, we store the HTML report which can be printed to PDF from the browser
  const fileKey = `reports/${reportId}-${nanoid(8)}.html`;
  const htmlBuffer = Buffer.from(html, "utf-8");

  try {
    const { url } = await storagePut(fileKey, htmlBuffer, "text/html");
    return { url, key: fileKey };
  } catch (err) {
    console.error("[PDF] Failed to upload report:", err);
    // Return a data URL as fallback
    const base64 = htmlBuffer.toString("base64");
    return {
      url: `data:text/html;base64,${base64}`,
      key: fileKey,
    };
  }
}
